# Generated by Django 5.2.8 on 2025-11-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=50)),
                ('Titulo', models.CharField(max_length=50)),
                ('Publicao', models.IntegerField()),
                ('Categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
