# Generated by Django 5.2.8 on 2025-11-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Matricula', models.CharField(max_length=50)),
                ('Senha', models.IntegerField(max_length=8)),
                ('cargo', models.CharField(max_length=13)),
            ],
        ),
    ]
