# Generated by Django 5.2.5 on 2025-11-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugb', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='bibliotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Senha', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Senha',
            field=models.IntegerField(),
        ),
    ]
