# Generated by Django 5.2.8 on 2025-11-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugb', '0003_bibliotecario_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='livros',
        ),
    ]
