# Generated by Django 5.2.8 on 2025-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugb', '0004_livro_delete_livros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
